stages:
  - build
  - deploy

build:
  stage: build
  image: docker:20.10.7
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker buildx create --use --name electionsassistantbuilder || docker buildx use electionsassistantbuilder
    - docker buildx inspect --bootstrap
  script:
    - echo "Building and pushing the Docker image"
    - >
      docker buildx build
      --platform linux/amd64
      --build-arg OPENAI_API_KEY=$OPENAI_API_KEY
      --tag $CI_REGISTRY/gitlab-mirco/elections-assistant:$CI_COMMIT_SHA
      --cache-from=type=registry,ref=$CI_REGISTRY/gitlab-mirco/elections-assistant:buildcache
      --cache-to=type=registry,ref=$CI_REGISTRY/gitlab-mirco/elections-assistant:buildcache,mode=max
      --push
      .

  timeout: 2h
  tags:
    - raspberrypi
  only:
    - branches

deploy:
  stage: deploy
  image: docker:20.10.7
  services:
    - docker:dind
  before_script:
    - echo "$KUBECONFIG" > /tmp/kubeconfig
    - export KUBECONFIG=/tmp/kubeconfig
  script:
    - sed -i "s|\$CI_REGISTRY|$CI_REGISTRY|g" k8s/stateful_set.yml
    - sed -i "s|\$CI_COMMIT_SHA|$CI_COMMIT_SHA|g" k8s/stateful_set.yml
    - kubectl get ns
    - kubectl -n elections-assistant apply -f k8s/stateful_set.yml
    - kubectl -n elections-assistant apply -f k8s/service.yml
  tags:
    - raspberrypi
  only:
    - main
