apiVersion: apps/v1
kind: Deployment
metadata:
  name: elections-programs
  namespace: elections-programs
  labels:
    app: elections-programs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: elections-programs
  template:
    metadata:
      labels:
        app: elections-programs
    spec:
      containers:
        - name: elections-programs-container
          image: $CI_REGISTRY/gitlab-mirco/elections-programs:$CI_COMMIT_SHA
          env:
          - name: API_USERNAME
            valueFrom:
              secretKeyRef:
                name: basic-auth-credentials
                key: username
          - name: API_PASSWORD
            valueFrom:
              secretKeyRef:
                name: basic-auth-credentials
                key: password
          volumeMounts:
            - name: faiss-storage
              mountPath: /app/faiss
          ports:
            - containerPort: 8000
      volumes:
        - name: faiss-storage
          persistentVolumeClaim:
            claimName: faiss-pvc
      imagePullSecrets:
        - name: gitlab-registry-secret
