apiVersion: v1
kind: Service
metadata:
  name: elections-assistant
  namespace: elections-assistant
spec:
  type: ClusterIP
  selector:
    app: elections-assistant
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000