apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elections-assistant
  namespace: elections-assistant
  labels:
    app: elections-assistant
spec:
  serviceName: "elections-assistant-headless"
  replicas: 2
  selector:
    matchLabels:
      app: elections-assistant
  template:
    metadata:
      labels:
        app: elections-assistant
    spec:
      containers:
        - name: elections-assistant-container
          image: $CI_REGISTRY/gitlab-mirco/elections-assistant:$CI_COMMIT_SHA
          env:
            - name: API_USERNAME
              valueFrom:
                secretKeyRef:
                  name: basic-auth-credentials
                  key: username
            - name: API_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: basic-auth-credentials
                  key: password
          volumeMounts:
            - name: faiss-storage
              mountPath: /app/faiss
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: gitlab-registry-secret
  volumeClaimTemplates:
    - metadata:
        name: faiss-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 400Mi
        storageClassName: longhorn-sc